language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

notifications:
  webhooks:
    urls:
        - https://zapier.com/hooks/catch/btkhbf/
    on_success: always
    on_failure: always
    on_start: never

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

after_success:
- ./gradlew jacocoRootReport coveralls
